In [ ]:
pip install tensorflow

In [2]:
import tensorflow as tf
print(tf.__version__)
tf.executing_eagerly()

2.19.0


True

In [3]:
tf.compat.v1.disable_eager_execution()

scalar=tf.constant(1, tf.int16, name='scalar') # rank or dimensions 0
vector=tf.constant([1,2,3], tf.int64,name='vecctor') #rank or dimensions 1
mat=tf.constant([[1,2,3],[4,5,6]], tf.int32, name='matrix') #rank or dimensions 2

print(vector.get_shape())
print(mat.shape)

tf.executing_eagerly()

(3,)
(2, 3)


False

In [4]:
tf.executing_eagerly()

False

In [11]:
# ENABLE EAGER EXECUTION

tf.compat.v1.enable_eager_execution() # cannot run this after disabling eager execution once in a notebook (restart runtime to execute this without disabling it)
tf.executing_eagerly()

ValueError: tf.enable_eager_execution must be called at program startup.

In [7]:
m_shape= tf.constant([[11,10],[13,12],[15,14]])
print(m_shape.shape)

(3, 2)


In [35]:
a=tf.constant(1, tf.int8, shape=[2,3], name='trial')
print(a)

with tf.compat.v1.Session() as sess: #this is required because disabling eager executing means it is in graph mode(need to create a session to execute tensors)
    tensor_value = sess.run(a)
    print("Tensor 'a' value:", tensor_value)
    print("\nTensor 'a' type:", type(tensor_value))

Tensor("trial_1:0", shape=(2, 3), dtype=int8)
Tensor 'a' value: [[1 1 1]
 [1 1 1]]

Tensor 'a' type: <class 'numpy.ndarray'>


In [33]:
tf.compat.v1.reset_default_graph() # resets the tensorflow graph, resetting the existing built graphs (name suffix like _1,_2 of tensors gets reset to 0 if one tensor executed many times)
print(a)

Tensor("trial:0", shape=(2, 3), dtype=int8)


In [39]:
tf.compat.v1.reset_default_graph() # use this for every new execution

decimal=tf.constant(12.34, tf.float16)
print(decimal)

alphabets=tf.constant('string', tf.string)
print(alphabets)


boolean=tf.constant([True, False], tf.bool)
print(boolean)

with tf.compat.v1.Session() as sess:
  print(sess.run(decimal))
  print(sess.run(alphabets))
  print(sess.run(boolean))

Tensor("Const:0", shape=(), dtype=float16)
Tensor("Const_1:0", shape=(), dtype=string)
Tensor("Const_2:0", shape=(2,), dtype=bool)
12.34
b'string'
[ True False]


In [43]:
tf.compat.v1.reset_default_graph()

zeroes=tf.zeros([2,2], tf.int8)
print(zeroes)

ones=tf.ones([2,3,2], tf.float16) # for 3d, first index=no. of 2d matrix, second and third index=rows and columns
print(ones)

with tf.compat.v1.Session() as sess:
  print(sess.run(zeroes))
  print(sess.run(ones))



Tensor("zeros:0", shape=(2, 2), dtype=int8)
Tensor("ones:0", shape=(2, 3, 2), dtype=float16)
[[0 0]
 [0 0]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [44]:
tf.compat.v1.reset_default_graph()

a_float=tf.constant(1, tf.float16)
a_int=tf.cast(a_float, tf.int16)

print(a_float)
print(a_int)

with tf.compat.v1.Session() as sess:
  print(sess.run(a_float))
  print(sess.run(a_int))

Tensor("Const:0", shape=(), dtype=float16)
Tensor("Cast:0", shape=(), dtype=int16)
1.0
1


In [46]:
import numpy as np

tf.compat.v1.reset_default_graph()

a=np.array([1,2,3,4])
b=tf.constant(a, tf.int16)

print(a)
print(b)

with tf.compat.v1.Session() as sess:
  print(sess.run(b))

[1 2 3 4]
Tensor("Const:0", shape=(4,), dtype=int16)
[1 2 3 4]


In [55]:
tf.compat.v1.reset_default_graph()

var1=tf.compat.v1.Variable(0, name='var1')

assign_op=tf.compat.v1.assign(var1, 10)

with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
    sess.run(assign_op)
    print(sess.run(var1))

10
