In [1]:
import torch
from torchvision import datasets
from torchvision.transforms import ToTensor
from torch.utils.data import DataLoader
from torch import nn
from torch import optim

# Getting Started

In [6]:
x=torch.rand(3)
print(x)
type(x)

tensor([0.6375, 0.7364, 0.7428])


torch.Tensor

In [138]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"Using {device} device")


Using cuda device


In [139]:
t1=torch.tensor([1,2,3,4,5])
print('1D tensor:',t1)

t2=torch.tensor([[1,2],[3,4],[5,6]])
print('\n2D Tensor:',t2)

t3=torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
print('\n3D Tensor:',t3)

1D tensor: tensor([1, 2, 3, 4, 5])

2D Tensor: tensor([[1, 2],
        [3, 4],
        [5, 6]])

3D Tensor: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [140]:
t4=torch.rand(2,3)
print('random 2x3 tensor:\n',t4)

t5=torch.zeros(2,3)
print('\n2x3 tensor filled with zeros:\n',t5)

t6=torch.ones(2,3)
print('\n2x3 tensor filled with ones:\n',t6)

t7=torch.empty(2,3)
print('\n2x3 empty tensor:\n',t7)

random 2x3 tensor:
 tensor([[0.0929, 0.8024, 0.5947],
        [0.1535, 0.9415, 0.4627]])

2x3 tensor filled with zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

2x3 tensor filled with ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

2x3 empty tensor:
 tensor([[ 1.1364e-03, -4.8785e-05,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [141]:
t8=torch.tensor([[1,2],[3,4],[5,6]])
print('2D tensor:\n',t8)

print('\nFirst row:',t8[0])

print('\nFirst column:',t8[:,0])

print('\nLast column:',t8[:,-1])

print('\nFirst 2 rows:\n',t8[:2])

2D tensor:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])

First row: tensor([1, 2])

First column: tensor([1, 3, 5])

Last column: tensor([2, 4, 6])

First 2 rows:
 tensor([[1, 2],
        [3, 4]])


In [142]:
t9=torch.tensor([[1,2],[3,4],[5,6]])
t9_reshape=t9.view(2,3)
print('Original 2D tensor:\n',t9)

print('\nReshaped 2D tensor:\n',t9_reshape)

Original 2D tensor:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])

Reshaped 2D tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [143]:
t10=torch.tensor([[1,2,3],[4,5,6]])
t11=torch.tensor([[10,20,30]])
add=t10+t11
print('Original 2D tensor:\n',t10)

print('\nAdded tensor:\n',add)

matmul=torch.matmul(t10, t10.T)
print('\nMatmul tensor:\n',matmul)

Original 2D tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])

Added tensor:
 tensor([[11, 22, 33],
        [14, 25, 36]])

Matmul tensor:
 tensor([[14, 32],
        [32, 77]])


In [144]:

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

tensor_size = (100, 100)  
a = torch.randn(tensor_size, device=device)  
b = torch.randn(tensor_size, device=device)  

c = a + b  


print("Current GPU memory usage:")
print(f"Allocated: {torch.cuda.memory_allocated(device) / (1024 ** 2):.2f} MB")
print(f"Cached: {torch.cuda.memory_reserved(device) / (1024 ** 2):.2f} MB")

Using device: cuda
Current GPU memory usage:
Allocated: 0.12 MB
Cached: 2.00 MB


In [25]:
import gc
gc.collect()
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
torch.cuda.empty_cache()
print(f"Allocated: {torch.cuda.memory_allocated(device) / (1024 ** 2):.2f} MB")
print(f"Cached: {torch.cuda.memory_reserved(device) / (1024 ** 2):.2f} MB")

Allocated: 0.00 MB
Cached: 0.00 MB


# Neural Network

In [2]:
training_data=datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)
test_data=datasets.FashionMNIST(
    root="data",
    train=False, #extracts test data
    download=True,
    transform=ToTensor()
)

batch_size=60
train_dataloader=DataLoader(training_data, batch_size)
test_dataloader=DataLoader(test_data, batch_size)

labels_map = {
    0: "T-Shirt",
    1: "Trouser",
    2: "Pullover",
    3: "Dress",
    4: "Coat",
    5: "Sandal",
    6: "Shirt",
    7: "Sneaker",
    8: "Bag",
    9: "Ankle Boot",
}

classes = list(labels_map.values())

In [149]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1=nn.Linear(2,4)
        self.fc2=nn.Linear(4,1)
    def forward(self,x):
        x=torch.relu(self.fc1(x))
        x=self.fc2(x)
        return x
model=SimpleNN()
print(model)

SimpleNN(
  (fc1): Linear(in_features=2, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=1, bias=True)
)


In [150]:
X_train=torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
y_train=torch.tensor([[0.0],[1.0],[1.0],[0.0]])

model=SimpleNN()
criterion=nn.MSELoss()
optimizer=optim.SGD(model.parameters(), lr=0.005)


for epoch in range(1000):
    model.train()
    outputs=model(X_train)
    loss=criterion(outputs, y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch+1}/1000], Loss: {loss.item():.4f}')

Epoch [100/1000], Loss: 0.3065
Epoch [200/1000], Loss: 0.2618
Epoch [300/1000], Loss: 0.2404
Epoch [400/1000], Loss: 0.2232
Epoch [500/1000], Loss: 0.2077
Epoch [600/1000], Loss: 0.1932
Epoch [700/1000], Loss: 0.1803
Epoch [800/1000], Loss: 0.1678
Epoch [900/1000], Loss: 0.1556
Epoch [1000/1000], Loss: 0.1436


In [151]:
model.eval()
with torch.no_grad():
    test_data=torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
    predictions=model(test_data)
    print(predictions)

tensor([[0.3884],
        [0.6384],
        [0.5996],
        [0.3633]])


In [3]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten=nn.Flatten()
        self.linear_relu_stack=nn.Sequential(
        nn.Linear(28*28,512),
        nn.ReLU(),
        nn.Linear(512,512),
        nn.ReLU(),
        nn.Linear(512,10)
        )
    def forward(self, x):
        x=self.flatten(x)
        logits=self.linear_relu_stack(x)
        return logits

model=NeuralNetwork()
print(model)    

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [4]:
loss_fn=nn.CrossEntropyLoss()
optimizer=optim.SGD(model.parameters(), lr=0.003)

def train(dataloader, model, loss_fn, optimizer):
    size=len(dataloader.dataset)
    model.train()
    for batch, (X,y) in enumerate(dataloader):
        pred=model(X)
        loss=loss_fn(pred, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        # if batch % 100 == 0:
    loss, current = loss.item(), (batch + 1) * len(X)
    print(f"loss: {loss}  [{current}/{size}]")
            
def test(dataloader, model, loss_fn):
    size=len(dataloader.dataset)    
    n_batches=len(dataloader)
    model.eval()
    test_loss, correct= 0,0
    with torch.no_grad():
        for X,y in dataloader:
            pred=model(X)
            test_loss+=loss_fn(pred, y).item()
            correct+=(pred.argmax(1)==y).type(torch.float).sum().item()
    test_loss/=n_batches
    correct/=size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [5]:
epochs=10
for i in range(epochs):
    print(f"Epoch {i+1}:\n")
    train(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)

Epoch 1:

loss: 1.5082645416259766  [60000/60000]
Test Error: 
 Accuracy: 60.0%, Avg loss: 1.473011 

Epoch 2:

loss: 1.0015138387680054  [60000/60000]
Test Error: 
 Accuracy: 66.0%, Avg loss: 0.959777 

Epoch 3:

loss: 0.846994161605835  [60000/60000]
Test Error: 
 Accuracy: 70.0%, Avg loss: 0.803486 

Epoch 4:

loss: 0.7590461373329163  [60000/60000]
Test Error: 
 Accuracy: 73.5%, Avg loss: 0.725632 

Epoch 5:

loss: 0.6968614459037781  [60000/60000]
Test Error: 
 Accuracy: 76.2%, Avg loss: 0.672210 

Epoch 6:

loss: 0.6495867371559143  [60000/60000]
Test Error: 
 Accuracy: 77.9%, Avg loss: 0.631773 

Epoch 7:

loss: 0.6136932373046875  [60000/60000]
Test Error: 
 Accuracy: 79.0%, Avg loss: 0.600784 

Epoch 8:

loss: 0.5865381360054016  [60000/60000]
Test Error: 
 Accuracy: 79.8%, Avg loss: 0.576731 

Epoch 9:

loss: 0.5661325454711914  [60000/60000]
Test Error: 
 Accuracy: 80.6%, Avg loss: 0.557673 

Epoch 10:

loss: 0.5501990914344788  [60000/60000]
Test Error: 
 Accuracy: 81.1%, A

In [6]:
model.eval()
with torch.no_grad():
    for i in range(5):
        X, y = test_data[i][0], test_data[i][1]
        pred = model(X)
        predicted, actual = classes[pred[0].argmax(0)], classes[y]
        print(f'Predicted: "{predicted}", Actual: "{actual}"')

Predicted: "Ankle Boot", Actual: "Ankle Boot"
Predicted: "Pullover", Actual: "Pullover"
Predicted: "Trouser", Actual: "Trouser"
Predicted: "Trouser", Actual: "Trouser"
Predicted: "Shirt", Actual: "Shirt"


In [13]:
for name, parameter in model.named_parameters():
    print(name, "--",parameter.size())

linear_relu_stack.0.weight -- torch.Size([512, 784])
linear_relu_stack.0.bias -- torch.Size([512])
linear_relu_stack.2.weight -- torch.Size([512, 512])
linear_relu_stack.2.bias -- torch.Size([512])
linear_relu_stack.4.weight -- torch.Size([10, 512])
linear_relu_stack.4.bias -- torch.Size([10])


In [ ]:
# Convolution 1D:
m = nn.Conv1d(16, 33, 3, stride=2)
input = torch.randn(20, 16, 50)
output = m(input)
print(input.size())
print(output.size())
# print(output)
print(m)

torch.Size([20, 16, 50])
torch.Size([20, 33, 24])
Conv1d(16, 33, kernel_size=(3,), stride=(2,))


In [20]:
# Convolution 2D

m1 = nn.Conv2d(16, 33, 3, stride=2)

m2 = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))

m3 = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2), dilation=(3, 1))
input = torch.randn(20, 16, 50, 100)
output1 = m1(input)
output2 = m2(input)
output3 = m3(input)

print(input.size())
print(output1.size())
print(output2.size())
print(output3.size())
# print(output)


torch.Size([20, 16, 50, 100])
torch.Size([20, 33, 24, 49])
torch.Size([20, 33, 28, 100])
torch.Size([20, 33, 26, 100])


In [23]:
# Convolution 3D

m1=nn.Conv3d(16, 33, 2, stride=2)
m2=nn.Conv3d(16, 33, (3, 5, 2), stride=(2, 1, 1), padding=(4, 2, 0))
input=torch.randn(20, 16, 10, 50, 50)
output1=m1(input)
output2=m2(input)
print(input.size())
print(output1.size())
print(output2.size())

torch.Size([20, 16, 10, 50, 50])
torch.Size([20, 33, 5, 25, 25])
torch.Size([20, 33, 8, 50, 49])


In [35]:
#dropout 
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten=nn.Flatten()
        self.linear_relu_stack=nn.Sequential(
        nn.Linear(28*28,512),
        nn.ReLU(),
        nn.Dropout(0.2),
        nn.Linear(512,512),
        nn.ReLU(),
        nn.Dropout(0.2),
        nn.Linear(512,10)
        )
    def forward(self, x):
        x=self.flatten(x)
        logits=self.linear_relu_stack(x)
        return logits

model=NeuralNetwork()
print(model) 

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.2, inplace=False)
    (3): Linear(in_features=512, out_features=512, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.2, inplace=False)
    (6): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [36]:
loss_fn=nn.CrossEntropyLoss()
optimizer=optim.AdamW(model.parameters(), lr=0.001)

def training(dataLoader, model, loss_fn, optimizer):
    size=len(dataLoader.dataset)
    model.train()
    for batch, (X,y) in enumerate(dataLoader):
        pred=model(X)
        loss=loss_fn(pred, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        # if batch % 100 == 0:
    loss, current = loss.item(), (batch + 1) * len(X)
    print(f"loss: {loss}  [{current}/{size}]")
            
def testing(dataLoader, model, loss_fn):
    size=len(dataLoader.dataset)    
    n_batches=len(dataLoader)
    model.eval()
    test_loss, correct= 0,0
    with torch.no_grad():
        for X,y in dataLoader:
            pred=model(X)
            test_loss+=loss_fn(pred, y).item()
            correct+=(pred.argmax(1)==y).type(torch.float).sum().item()
    test_loss/=n_batches
    correct/=size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
    
epochs=10
for i in range(epochs):
    print(f"Epoch {i+1}:\n")
    training(train_dataloader, model, loss_fn, optimizer)
    testing(test_dataloader, model, loss_fn)

Epoch 1:

loss: 0.43239572644233704  [60000/60000]
Test Error: 
 Accuracy: 83.1%, Avg loss: 0.451494 

Epoch 2:

loss: 0.38935422897338867  [60000/60000]
Test Error: 
 Accuracy: 85.3%, Avg loss: 0.399360 

Epoch 3:

loss: 0.3372545540332794  [60000/60000]
Test Error: 
 Accuracy: 86.1%, Avg loss: 0.378803 

Epoch 4:

loss: 0.3212348222732544  [60000/60000]
Test Error: 
 Accuracy: 86.9%, Avg loss: 0.354543 

Epoch 5:

loss: 0.36041709780693054  [60000/60000]
Test Error: 
 Accuracy: 87.4%, Avg loss: 0.342899 

Epoch 6:

loss: 0.2732643187046051  [60000/60000]
Test Error: 
 Accuracy: 87.1%, Avg loss: 0.352029 

Epoch 7:

loss: 0.27149611711502075  [60000/60000]
Test Error: 
 Accuracy: 87.3%, Avg loss: 0.341071 

Epoch 8:

loss: 0.3338007628917694  [60000/60000]
Test Error: 
 Accuracy: 87.6%, Avg loss: 0.334360 

Epoch 9:

loss: 0.22312143445014954  [60000/60000]
Test Error: 
 Accuracy: 87.6%, Avg loss: 0.341208 

Epoch 10:

loss: 0.26701176166534424  [60000/60000]
Test Error: 
 Accuracy: 8

In [38]:
model.eval()
with torch.no_grad():
    for i in range(15,20):
        X, y = test_data[i][0], test_data[i][1]
        pred = model(X)
        predicted, actual = classes[pred[0].argmax(0)], classes[y]
        print(f'Predicted: "{predicted}", Actual: "{actual}"')

Predicted: "Trouser", Actual: "Trouser"
Predicted: "Pullover", Actual: "Pullover"
Predicted: "Pullover", Actual: "Coat"
Predicted: "Bag", Actual: "Bag"
Predicted: "T-Shirt", Actual: "T-Shirt"


In [49]:
#CNN

class CNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1= nn.Conv2d(1, 64, 2)
        self.conv2= nn.Conv2d(64, 128, 2)
        
        self.relu= nn.ReLU()
        self.pool= nn.MaxPool2d(2)
        self.fc_shape=None
        self.size_tracker(torch.randn(1, 1, 28, 28))
        
        self.fc= nn.Linear(self.fc_shape, 10)
        self.flat= nn.Flatten()
        
    def size_tracker(self, x):
        x= self.pool(self.relu(self.conv1(x)))
        x= self.pool(self.relu(self.conv2(x)))
        x= self.fc(x)
        self.fc_shape= x[0].shape[0]*x[0].shape[1]*x[0].shape[2]
        
    def forward(self, x):
        x= self.pool(self.relu(self.conv1(x)))
        x= self.pool(self.relu(self.conv2(x)))
        x= self.flat(x)
        x= self.fc(x)
        return x

model=CNN()
print(model)
    

AttributeError: 'CNN' object has no attribute 'fc'

In [43]:
loss_fn=nn.CrossEntropyLoss()
optimizer=optim.AdamW(model.parameters(), lr=0.0001)


def training(dataLoader, model, loss_fn, optimizer):
    size=len(dataLoader.dataset)
    model.train()
    for batch, (X,y) in enumerate(dataLoader):
        pred=model(X)
        loss=loss_fn(pred, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        # if batch % 100 == 0:
    loss, current = loss.item(), (batch + 1) * len(X)
    print(f"loss: {loss}  [{current}/{size}]")

def testing(dataLoader, model, loss_fn):
    size=len(dataLoader.dataset)    
    n_batches=len(dataLoader)
    model.eval()
    test_loss, correct= 0,0
    with torch.no_grad():
        for X,y in dataLoader:
            pred=model(X)
            test_loss+=loss_fn(pred, y).item()
            correct+=(pred.argmax(1)==y).type(torch.float).sum().item()
    test_loss/=n_batches
    correct/=size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [44]:
epoch=10
for i in range(epoch):
    print(f"Epoch {i+1}:\n")
    training(train_dataloader, model, loss_fn, optimizer)
    testing(test_dataloader, model, loss_fn)

Epoch 1:



RuntimeError: mat1 and mat2 shapes cannot be multiplied (60x2304 and 1024x512)